version: '3.8'
services:
  app:
    build:
      context: ..
    image: 'hotel-service:latest'
    ports:
      - "8080:8080"
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/booking_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booking_db
